nome : gerar animação

sobre :
  #executa automaticamente a cada 24 horas
  agendador :
    -cron : " 0 */24 * * * " 
  
  # permite executar manualmente o trabalho a qualquer momento
  fluxo de trabalho_dispatch :
  
  #executa em cada push no branch master
  empurra :
    galhos :
    -mestre​
    
  

negócios :
  gerar :
    permissões :
      conteúdo : escrever
    executado : ubuntu-mais recente
    minutos de tempo limite : 5
    
    passos :
      # gera um jogo de cobra a partir de um gráfico de contribuições de um usuário do github (<github_user_name>), gera uma animação SVG em <svg_out_path>
      - nome : gerar github-contribution-grid-snake.svg
        usos : Platane/snk/svg-only@v3
        com :
          github_user_name : ${{github.repository_owner}}
          saídas : |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          
          
      # envia o conteúdo de <build_dir> para um branch
      # o conteúdo estará disponível em https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> ou como página do github
      - nome : envie github-contribution-grid-snake.svg para o branch de saída
        usos : crazy-max/ghaction-github-pages@v3.1.0
        com :
          target_branch : saída
          build_dir : dist
        ambientes :
          GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
